version: '2'

services:

  nginx:
    image: mercuriete/laravel-redis-nginx
    ports:
      - "80:80"

  php:
    build: .
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
      - "APP_DEBUG=true"
      - "APP_KEY=base64:blx5HrJew5Yfc3vmqv6t1Qi5cJarWEk7Wn3+ZACDks0="

  database:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=common404"
      - "MYSQL_DATABASE=laravel"

  redis:
    image: redis:4.0

